version: '3'

services: 
  flask:
    build: ./Flask-Docker/
    ports: 
      - 8000:8000
    network_mode: bridge  

  nginx:
    build: ./nginx/
    container_name: nginx
    restart: always
    network_mode: host